language: java
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - bxb@inf.uni-konstanz.de
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
